#!/usr/bin/env python3
"""
Jupiter Seed 4B — Review Queue Generator
=========================================
Generates all review-queue representations from a single authoritative JSONL source:
  - training/jupiter_seed_4b/data/human_review_queue.jsonl  (authoritative)
  - docs/jupiter_seed_4b/ARABIC_HUMAN_REVIEW_QUEUE.md       (generated)
  - docs/jupiter_seed_4b/REVIEWER_TEMPLATE.csv              (generated, UTF-8 BOM)
  - docs/jupiter_seed_4b/REVIEW_QUEUE_MANIFEST.json         (generated)

All reviewer judgment fields remain EMPTY. Software must never populate them.

Usage:
    python3 generate_review_queue.py
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import logging
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
log = logging.getLogger(__name__)

REVIEWER_JUDGMENT_FIELDS = [
    "reviewer_name",
    "reviewer_experience",
    "review_date",
    "accuracy_score",
    "fluency_score",
    "gcc_appropriateness_score",
    "domain_terminology_score",
    "factuality_score",
    "verdict",
    "corrected_wording",
    "rejection_reason",
    "comments",
]


def sha256_of(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def get_git_commit() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True, text=True, check=True
        )
        return result.stdout.strip()
    except Exception:
        return "unknown"


def load_queue(path: Path) -> List[Dict[str, Any]]:
    records = []
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def generate_markdown(records: List[Dict], output_path: Path) -> str:
    """Generate Markdown review document from JSONL. Returns SHA-256 of output."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        "# Jupiter Seed 4B: Arabic Human Review Queue",
        "",
        f"**Generated:** {now}",
        "**Source:** `training/jupiter_seed_4b/data/human_review_queue.jsonl`",
        "**Status:** PENDING HUMAN REVIEW",
        "",
        "> **Warning:** This document is generated automatically from the authoritative JSONL source.",
        "> Do not edit this file manually. Do not mark any record as human-approved.",
        "> Software must never populate reviewer judgment fields.",
        "",
        f"**Total records:** {len(records)}",
        "",
        "## Coverage",
        "",
    ]

    # Coverage summary
    domains = {}
    langs = {}
    splits = {}
    for r in records:
        domains[r["domain"]] = domains.get(r["domain"], 0) + 1
        langs[r["language"]] = langs.get(r["language"], 0) + 1
        splits[r["split"]] = splits.get(r["split"], 0) + 1

    lines += ["| Category | Coverage |", "| :--- | :--- |"]
    lines.append(f"| Domains | {', '.join(f'{d}: {c}' for d, c in sorted(domains.items()))} |")
    lines.append(f"| Languages | {', '.join(f'{l}: {c}' for l, c in sorted(langs.items()))} |")
    lines.append(f"| Splits | {', '.join(f'{s}: {c}' for s, c in sorted(splits.items()))} |")

    lines += [
        "",
        "## Review Records",
        "",
        "| # | Example ID | Split | Domain | Language | Task Type | Difficulty | Provenance | Source | Prompt (first 80 chars) | Response (first 80 chars) | Integrity Flags |",
        "| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |",
    ]

    for i, r in enumerate(records, 1):
        prompt_preview = str(r.get("prompt", ""))[:80].replace("|", "\\|").replace("\n", " ")
        resp_preview = str(r.get("response", ""))[:80].replace("|", "\\|").replace("\n", " ")
        flags = []
        if not r.get("language_contract_passed", True):
            flags.append("LANG_FAIL")
        if r.get("factuality_review_status") == "human_approved":
            flags.append("ILLEGAL_APPROVAL")
        flags_str = ", ".join(flags) if flags else "OK"

        lines.append(
            f"| {i} | `{r['example_id']}` | {r['split']} | {r['domain']} | "
            f"{r['language']} | {r['task_type']} | {r['difficulty']} | "
            f"{r.get('provenance_type', 'N/A')} | {r.get('source_name', 'N/A')} | "
            f"{prompt_preview} | {resp_preview} | {flags_str} |"
        )

    lines += [
        "",
        "## Reviewer Instructions",
        "",
        "For each record, please score the following dimensions and provide a final verdict.",
        "**Do not use AI tools to complete this review. All judgments must be independent human assessments.**",
        "",
        "| Dimension | Description |",
        "| :--- | :--- |",
        "| Accuracy | Is the response factually correct? |",
        "| Fluency | Is the Arabic/English grammatically correct and natural? |",
        "| GCC Appropriateness | Is the content culturally and professionally appropriate for GCC enterprise use? |",
        "| Domain Terminology | Are domain-specific terms (Islamic finance, banking, telecom, etc.) used correctly? |",
        "| Factuality | Does the response avoid inventing facts? |",
        "| Verdict | ACCEPT, REVISE, or REJECT |",
        "",
        "**AI-ASSISTED INTERNAL CONTENT AUDIT — NOT HUMAN APPROVAL**",
    ]

    content = "\n".join(lines) + "\n"
    with output_path.open("w", encoding="utf-8") as fh:
        fh.write(content)
    log.info("Markdown written to %s (%d records)", output_path, len(records))
    return sha256_of(content)


def generate_csv(records: List[Dict], output_path: Path) -> str:
    """Generate UTF-8 BOM CSV for Excel. Returns SHA-256 of output."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "example_id", "split", "domain", "language",
        "prompt_language", "response_language",
        "task_type", "difficulty", "provenance_type",
        "source_name", "source_url",
        "prompt", "response",
        "arabic_character_count_prompt", "arabic_character_count_response",
        "arabic_ratio_prompt", "arabic_ratio_response",
        "language_contract_passed",
        "content_sha256",
        "integrity_flags",
    ] + REVIEWER_JUDGMENT_FIELDS

    rows = []
    for r in records:
        flags = []
        if not r.get("language_contract_passed", True):
            flags.append("LANG_FAIL")
        if r.get("factuality_review_status") == "human_approved":
            flags.append("ILLEGAL_APPROVAL")

        row = {
            "example_id": r["example_id"],
            "split": r["split"],
            "domain": r["domain"],
            "language": r["language"],
            "prompt_language": r.get("prompt_language", ""),
            "response_language": r.get("response_language", ""),
            "task_type": r["task_type"],
            "difficulty": r["difficulty"],
            "provenance_type": r.get("provenance_type", ""),
            "source_name": r.get("source_name", ""),
            "source_url": r.get("source_url", ""),
            "prompt": r["prompt"],
            "response": r["response"],
            "arabic_character_count_prompt": r.get("arabic_character_count_prompt", 0),
            "arabic_character_count_response": r.get("arabic_character_count_response", 0),
            "arabic_ratio_prompt": r.get("arabic_ratio_prompt", 0),
            "arabic_ratio_response": r.get("arabic_ratio_response", 0),
            "language_contract_passed": r.get("language_contract_passed", True),
            "content_sha256": r.get("content_sha256", ""),
            "integrity_flags": ", ".join(flags) if flags else "OK",
        }
        # All reviewer judgment fields remain EMPTY
        for field in REVIEWER_JUDGMENT_FIELDS:
            row[field] = ""

        rows.append(row)

    # Write with UTF-8 BOM for Excel compatibility
    with output_path.open("w", encoding="utf-8-sig", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    # Compute SHA-256 of the file content
    file_bytes = output_path.read_bytes()
    csv_sha = hashlib.sha256(file_bytes).hexdigest()
    log.info("CSV written to %s (%d records)", output_path, len(records))
    return csv_sha


def generate_manifest(
    records: List[Dict],
    jsonl_path: Path,
    md_sha: str,
    csv_sha: str,
    manifest_path: Path,
) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    git_commit = get_git_commit()

    # JSONL SHA-256
    jsonl_bytes = jsonl_path.read_bytes()
    jsonl_sha = hashlib.sha256(jsonl_bytes).hexdigest()

    # Per-record content hashes
    record_hashes = [r["content_sha256"] for r in records]
    ordered_hash = sha256_of("|".join(record_hashes))

    manifest = {
        "queue_version": "1.1.1",
        "generation_timestamp": now,
        "git_commit": git_commit,
        "source_jsonl": str(jsonl_path),
        "source_jsonl_sha256": jsonl_sha,
        "record_count": len(records),
        "ordered_record_ids": [r["example_id"] for r in records],
        "per_record_content_hashes": {r["example_id"]: r["content_sha256"] for r in records},
        "ordered_queue_sha256": ordered_hash,
        "markdown_sha256": md_sha,
        "csv_sha256": csv_sha,
        "approval_status": "PENDING HUMAN REVIEW",
        "reviewer_fields_populated_by_software": False,
        "coverage": {
            "domains": sorted(set(r["domain"] for r in records)),
            "languages": sorted(set(r["language"] for r in records)),
            "splits": sorted(set(r["split"] for r in records)),
        },
        "integrity_checks": {
            "duplicate_prompts": len(records) - len(set(r["prompt"] for r in records)),
            "duplicate_responses": len(records) - len(set(r["response"] for r in records)),
            "language_contract_violations": sum(
                1 for r in records if not r.get("language_contract_passed", True)
            ),
            "illegal_approvals": sum(
                1 for r in records if r.get("factuality_review_status") == "human_approved"
            ),
        },
    }

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    with manifest_path.open("w", encoding="utf-8") as fh:
        json.dump(manifest, fh, ensure_ascii=False, indent=2)
    log.info("Manifest written to %s", manifest_path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Jupiter Seed 4B — Review Queue Generator")
    parser.add_argument("--data-dir", type=Path,
                        default=Path("training/jupiter_seed_4b/data"))
    parser.add_argument("--docs-dir", type=Path,
                        default=Path("docs/jupiter_seed_4b"))
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    jsonl_path = args.data_dir / "human_review_queue.jsonl"
    md_path = args.docs_dir / "ARABIC_HUMAN_REVIEW_QUEUE.md"
    csv_path = args.docs_dir / "REVIEWER_TEMPLATE.csv"
    manifest_path = args.docs_dir / "REVIEW_QUEUE_MANIFEST.json"

    if not jsonl_path.exists():
        log.error("JSONL not found: %s", jsonl_path)
        sys.exit(1)

    records = load_queue(jsonl_path)
    log.info("Loaded %d records from %s", len(records), jsonl_path)

    if len(records) != 50:
        log.error("Expected exactly 50 records, got %d", len(records))
        sys.exit(1)

    # Integrity checks
    dup_prompts = len(records) - len(set(r["prompt"] for r in records))
    dup_responses = len(records) - len(set(r["response"] for r in records))
    lang_violations = sum(1 for r in records if not r.get("language_contract_passed", True))

    if dup_prompts > 0:
        log.error("Duplicate prompts in queue: %d", dup_prompts)
        sys.exit(1)
    if dup_responses > 0:
        log.error("Duplicate responses in queue: %d", dup_responses)
        sys.exit(1)
    if lang_violations > 0:
        log.error("Language contract violations in queue: %d", lang_violations)
        sys.exit(1)

    log.info("Queue integrity checks passed.")

    md_sha = generate_markdown(records, md_path)
    csv_sha = generate_csv(records, csv_path)
    generate_manifest(records, jsonl_path, md_sha, csv_sha, manifest_path)

    log.info("All review queue representations generated successfully.")
    log.info("JSONL, Markdown, and CSV all contain the same %d records.", len(records))


if __name__ == "__main__":
    main()
