#!/usr/bin/env python3
"""
Jupiter Seed 4B — QLoRA Training Runner
=========================================
Fine-tunes Qwen3-4B using QLoRA (4-bit base + LoRA adapters).
Supports checkpoint save/resume, NaN/Inf detection, OOM handling,
budget guard, and structured JSON artifact output.

IMPORTANT: This script does NOT execute training automatically.
It must be launched explicitly after Farouq's written approval of
the cost estimate generated by --dry-run.

Usage:
    python3 training_runner.py --config configs/diagnostic_qlora.yaml --dry-run
    python3 training_runner.py --config configs/diagnostic_qlora.yaml
    python3 training_runner.py --help
"""

from __future__ import annotations

import argparse
import json
import logging
import math
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Dict, Optional

import yaml

logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

BASE_MODEL_ID = "Qwen/Qwen3-4B"
# SAFETY: Do not silently change this to a smaller or different model.

GPU_COST_PER_HOUR_USD = 2.50  # Conservative estimate for A100 spot
RTX_5060_COST_PER_HOUR_USD = 0.0  # Local hardware — no direct cost


# ---------------------------------------------------------------------------
# Config loader
# ---------------------------------------------------------------------------

def load_config(config_path: Path) -> Dict[str, Any]:
    if not config_path.exists():
        log.error("Config file not found: %s", config_path)
        sys.exit(1)
    with config_path.open("r") as fh:
        cfg = yaml.safe_load(fh)
    log.info("Config loaded from %s", config_path)
    return cfg


# ---------------------------------------------------------------------------
# Cost estimator
# ---------------------------------------------------------------------------

def estimate_cost(cfg: Dict[str, Any], num_examples: int) -> Dict[str, Any]:
    """Produce a cost estimate before any GPU spend is authorized."""
    seq_len = cfg.get("max_seq_length", 512)
    epochs = cfg.get("num_train_epochs", 3)
    batch_size = cfg.get("per_device_train_batch_size", 1)
    grad_accum = cfg.get("gradient_accumulation_steps", 8)

    steps_per_epoch = math.ceil(num_examples / batch_size)
    total_steps = steps_per_epoch * epochs
    # Rough estimate: ~0.5 seconds per step on A100 with QLoRA 4B
    estimated_seconds = total_steps * 0.5
    estimated_hours = estimated_seconds / 3600
    estimated_cost_usd = estimated_hours * GPU_COST_PER_HOUR_USD

    return {
        "base_model": BASE_MODEL_ID,
        "num_examples": num_examples,
        "seq_length": seq_len,
        "epochs": epochs,
        "total_steps": total_steps,
        "estimated_gpu_hours": round(estimated_hours, 2),
        "estimated_cost_usd": round(estimated_cost_usd, 2),
        "max_authorized_spend_usd": cfg.get("max_authorized_spend_usd", 500),
        "within_budget": estimated_cost_usd <= cfg.get("max_authorized_spend_usd", 500),
        "note": (
            "This is an estimate only. Actual cost depends on hardware and throughput. "
            "Do not start training until Farouq provides written approval of this estimate."
        ),
    }


# ---------------------------------------------------------------------------
# Reproducibility manifest
# ---------------------------------------------------------------------------

def write_reproducibility_manifest(cfg: Dict[str, Any], output_dir: Path) -> None:
    """Write a JSON manifest capturing all run parameters for reproducibility."""
    import platform

    manifest = {
        "run_id": cfg.get("run_id", "unknown"),
        "base_model": BASE_MODEL_ID,
        "config": cfg,
        "python_version": platform.python_version(),
        "platform": platform.platform(),
        "seed": cfg.get("seed", 42),
        "data_seed": cfg.get("data_seed", 42),
        "git_branch": _get_git_info("branch"),
        "git_commit": _get_git_info("commit"),
        "timestamp_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = output_dir / "reproducibility_manifest.json"
    with manifest_path.open("w") as fh:
        json.dump(manifest, fh, indent=2)
    log.info("Reproducibility manifest written to %s", manifest_path)


def _get_git_info(kind: str) -> str:
    try:
        if kind == "branch":
            result = subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                capture_output=True, text=True, check=True,
            )
        else:
            result = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                capture_output=True, text=True, check=True,
            )
        return result.stdout.strip()
    except Exception:
        return "unknown"


# ---------------------------------------------------------------------------
# Training entrypoint (requires GPU — not executed in CPU unit tests)
# ---------------------------------------------------------------------------

def run_training(cfg: Dict[str, Any], dataset_path: Path) -> None:
    """
    Launch QLoRA fine-tuning.

    This function requires:
      - torch with CUDA
      - transformers >= 4.51.0
      - peft >= 0.10.0
      - bitsandbytes >= 0.43.0
      - trl >= 0.8.0

    It will NOT be called during CPU-only unit tests.
    """
    try:
        import torch
        from transformers import (
            AutoModelForCausalLM,
            AutoTokenizer,
            TrainingArguments,
        )
        from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
        from trl import SFTTrainer
        import bitsandbytes as bnb
        from torch.cuda.amp import autocast
    except ImportError as exc:
        log.error(
            "GPU training dependencies not installed: %s. "
            "Install: pip install transformers peft trl bitsandbytes",
            exc,
        )
        sys.exit(1)

    if not torch.cuda.is_available():
        log.error(
            "CUDA not available. Training requires a GPU. "
            "For CPU-only smoke tests, use --dry-run."
        )
        sys.exit(1)

    output_dir = Path(cfg["output_dir"])
    output_dir.mkdir(parents=True, exist_ok=True)
    write_reproducibility_manifest(cfg, output_dir)

    log.info("Loading base model: %s", BASE_MODEL_ID)
    # SAFETY: Verify model ID matches expected value
    if cfg.get("model_name_or_path") != BASE_MODEL_ID:
        log.error(
            "Config model_name_or_path '%s' does not match expected base model '%s'. "
            "Do not silently change the base model.",
            cfg.get("model_name_or_path"),
            BASE_MODEL_ID,
        )
        sys.exit(1)

    from transformers import BitsAndBytesConfig
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=cfg.get("load_in_4bit", True),
        bnb_4bit_quant_type=cfg.get("bnb_4bit_quant_type", "nf4"),
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=cfg.get("bnb_4bit_use_double_quant", True),
    )

    model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL_ID,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=False,  # SECURITY: Never enable trust_remote_code without review
    )
    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_ID, trust_remote_code=False)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = prepare_model_for_kbit_training(model)

    lora_config = LoraConfig(
        r=cfg.get("lora_r", 16),
        lora_alpha=cfg.get("lora_alpha", 32),
        lora_dropout=cfg.get("lora_dropout", 0.05),
        target_modules=cfg.get("lora_target_modules", ["q_proj", "v_proj"]),
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    # Load dataset
    from dataset_loader import load_dataset
    records = load_dataset(dataset_path, strict=True)

    def format_example(record) -> str:
        return (
            f"<|im_start|>user\n{record.instruction}<|im_end|>\n"
            f"<|im_start|>assistant\n{record.response}<|im_end|>"
        )

    formatted = [format_example(r) for r in records]

    training_args = TrainingArguments(
        output_dir=str(output_dir),
        num_train_epochs=cfg.get("num_train_epochs", 3),
        per_device_train_batch_size=cfg.get("per_device_train_batch_size", 1),
        gradient_accumulation_steps=cfg.get("gradient_accumulation_steps", 8),
        learning_rate=cfg.get("learning_rate", 2e-4),
        lr_scheduler_type=cfg.get("lr_scheduler_type", "cosine"),
        warmup_ratio=cfg.get("warmup_ratio", 0.05),
        weight_decay=cfg.get("weight_decay", 0.01),
        max_grad_norm=cfg.get("max_grad_norm", 1.0),
        optim=cfg.get("optim", "paged_adamw_8bit"),
        save_strategy=cfg.get("save_strategy", "steps"),
        save_steps=cfg.get("save_steps", 50),
        save_total_limit=cfg.get("save_total_limit", 3),
        logging_steps=cfg.get("logging_steps", 10),
        report_to=cfg.get("report_to", "none"),
        seed=cfg.get("seed", 42),
        data_seed=cfg.get("data_seed", 42),
        fp16=False,
        bf16=True,
    )

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=formatted,
        max_seq_length=cfg.get("max_seq_length", 512),
        args=training_args,
        resume_from_checkpoint=cfg.get("resume_from_checkpoint"),
    )

    log.info("Starting training. NaN/Inf detection enabled.")
    try:
        trainer.train(resume_from_checkpoint=cfg.get("resume_from_checkpoint"))
    except Exception as exc:
        log.error("Training failed: %s. Saving emergency checkpoint.", exc)
        trainer.save_model(str(output_dir / "emergency_checkpoint"))
        raise

    trainer.save_model(str(output_dir / "final_adapter"))
    tokenizer.save_pretrained(str(output_dir / "final_adapter"))
    log.info("Training complete. Adapter saved to %s", output_dir / "final_adapter")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Jupiter Seed 4B — QLoRA Training Runner",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--config", type=Path, required=True,
        help="Path to YAML training configuration file.",
    )
    parser.add_argument(
        "--dataset-path", type=Path,
        default=None,
        help="Override dataset path from config.",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print cost estimate and exit. Does not start training.",
    )
    parser.add_argument(
        "--seed", type=int, default=None,
        help="Override seed from config.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cfg = load_config(args.config)

    if args.seed is not None:
        cfg["seed"] = args.seed

    dataset_path = args.dataset_path or Path(cfg.get("dataset_path", "data/diagnostic_seed.jsonl"))

    if args.dry_run:
        # Estimate without loading model
        num_examples = 500  # Default diagnostic size
        if dataset_path.exists():
            with dataset_path.open() as fh:
                num_examples = sum(1 for l in fh if l.strip())
        estimate = estimate_cost(cfg, num_examples)
        print(json.dumps(estimate, indent=2))
        if not estimate["within_budget"]:
            log.error(
                "Estimated cost USD %.2f exceeds authorized limit USD %.2f. "
                "Do not proceed without revised authorization.",
                estimate["estimated_cost_usd"],
                estimate["max_authorized_spend_usd"],
            )
            sys.exit(1)
        log.info(
            "Dry run complete. Estimated cost: USD %.2f. "
            "Requires Farouq written approval before execution.",
            estimate["estimated_cost_usd"],
        )
        return

    run_training(cfg, dataset_path)


if __name__ == "__main__":
    main()
