#!/usr/bin/env python3
"""
Jupiter Seed 4B — QLoRA Training Runner
=========================================
Fine-tunes Qwen3-4B using QLoRA (4-bit base + LoRA adapters).
Supports checkpoint save/resume, NaN/Inf detection, OOM handling,
budget guard, and structured JSON artifact output.

IMPORTANT: This script does NOT execute training automatically.
It must be launched explicitly after Farouq's written approval of
the cost estimate generated by --dry-run.

Usage:
    python3 training_runner.py --config configs/diagnostic_qlora.yaml --dry-run
    python3 training_runner.py --config configs/diagnostic_qlora.yaml
    python3 training_runner.py --help
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import math
import os
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any, Callable, Dict, Optional

import yaml

logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

BASE_MODEL_ID = "Qwen/Qwen3-4B"
# SAFETY: Do not silently change this to a smaller or different model.

GPU_COST_PER_HOUR_USD = 2.50  # Conservative estimate for A100 spot
RTX_5060_COST_PER_HOUR_USD = 0.0  # Local hardware — no direct cost


# ---------------------------------------------------------------------------
# Config loader
# ---------------------------------------------------------------------------

def load_config(config_path: Path) -> Dict[str, Any]:
    if not config_path.exists():
        log.error("Config file not found: %s", config_path)
        sys.exit(1)
    with config_path.open("r", encoding="utf-8") as fh:
        cfg = yaml.safe_load(fh)
    log.info("Config loaded from %s", config_path)
    return cfg


# ---------------------------------------------------------------------------
# Cost estimator
# ---------------------------------------------------------------------------

def estimate_cost(cfg: Dict[str, Any], num_examples: int) -> Dict[str, Any]:
    """Produce a cost estimate before any GPU spend is authorized."""
    seq_len = cfg.get("max_seq_length", 512)
    epochs = cfg.get("num_train_epochs", 3)
    batch_size = cfg.get("per_device_train_batch_size", 1)
    grad_accum = cfg.get("gradient_accumulation_steps", 8)

    steps_per_epoch = math.ceil(num_examples / batch_size)
    total_steps = steps_per_epoch * epochs
    # Rough estimate: ~0.5 seconds per step on A100 with QLoRA 4B
    estimated_seconds = total_steps * 0.5
    estimated_hours = estimated_seconds / 3600
    estimated_cost_usd = estimated_hours * GPU_COST_PER_HOUR_USD

    return {
        "base_model": BASE_MODEL_ID,
        "num_examples": num_examples,
        "seq_length": seq_len,
        "epochs": epochs,
        "total_steps": total_steps,
        "estimated_gpu_hours": round(estimated_hours, 2),
        "estimated_cost_usd": round(estimated_cost_usd, 2),
        "max_authorized_spend_usd": cfg.get("max_authorized_spend_usd", 500),
        "within_budget": estimated_cost_usd <= cfg.get("max_authorized_spend_usd", 500),
        "note": (
            "This is an estimate only. Actual cost depends on hardware and throughput. "
            "Do not start training until Farouq provides written approval of this estimate."
        ),
    }


# ---------------------------------------------------------------------------
# Reproducibility manifest
# ---------------------------------------------------------------------------

def write_reproducibility_manifest(cfg: Dict[str, Any], output_dir: Path) -> None:
    """Write a JSON manifest capturing all run parameters for reproducibility."""
    import platform

    manifest = {
        "run_id": cfg.get("run_id", "unknown"),
        "base_model": BASE_MODEL_ID,
        "config": cfg,
        "python_version": platform.python_version(),
        "platform": platform.platform(),
        "seed": cfg.get("seed", 42),
        "data_seed": cfg.get("data_seed", 42),
        "git_branch": _get_git_info("branch"),
        "git_commit": _get_git_info("commit"),
        "timestamp_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = output_dir / "reproducibility_manifest.json"
    with manifest_path.open("w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)
    log.info("Reproducibility manifest written to %s", manifest_path)


def _get_git_info(kind: str) -> str:
    try:
        if kind == "branch":
            result = subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                capture_output=True, text=True, check=True,
            )
        else:
            result = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                capture_output=True, text=True, check=True,
            )
        return result.stdout.strip()
    except Exception:
        return "unknown"


# ---------------------------------------------------------------------------
# Training entrypoint (requires GPU — not executed in CPU unit tests)
# ---------------------------------------------------------------------------

def run_training(cfg: Dict[str, Any], dataset_path: Path) -> None:
    """
    Launch QLoRA fine-tuning.

    This function requires:
      - torch with CUDA
      - transformers >= 4.51.0
      - peft >= 0.10.0
      - bitsandbytes >= 0.43.0
      - trl >= 0.8.0

    It will NOT be called during CPU-only unit tests.
    """
    try:
        import torch
        from transformers import (
            AutoModelForCausalLM,
            AutoTokenizer,
            TrainingArguments,
        )
        from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
        from trl import SFTTrainer
        import bitsandbytes as bnb
        from torch.cuda.amp import autocast
    except ImportError as exc:
        log.error(
            "GPU training dependencies not installed: %s. "
            "Install: pip install transformers peft trl bitsandbytes",
            exc,
        )
        sys.exit(1)

    if not torch.cuda.is_available():
        log.error(
            "CUDA not available. Training requires a GPU. "
            "For CPU-only smoke tests, use --dry-run."
        )
        sys.exit(1)

    output_dir = Path(cfg["output_dir"])
    output_dir.mkdir(parents=True, exist_ok=True)
    write_reproducibility_manifest(cfg, output_dir)

    log.info("Loading base model: %s", BASE_MODEL_ID)
    # SAFETY: Verify model ID matches expected value
    if cfg.get("model_name_or_path") != BASE_MODEL_ID:
        log.error(
            "Config model_name_or_path '%s' does not match expected base model '%s'. "
            "Do not silently change the base model.",
            cfg.get("model_name_or_path"),
            BASE_MODEL_ID,
        )
        sys.exit(1)

    from transformers import BitsAndBytesConfig
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=cfg.get("load_in_4bit", True),
        bnb_4bit_quant_type=cfg.get("bnb_4bit_quant_type", "nf4"),
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=cfg.get("bnb_4bit_use_double_quant", True),
    )

    model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL_ID,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=False,  # SECURITY: Never enable trust_remote_code without review
    )
    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_ID, trust_remote_code=False)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = prepare_model_for_kbit_training(model)

    lora_config = LoraConfig(
        r=cfg.get("lora_r", 16),
        lora_alpha=cfg.get("lora_alpha", 32),
        lora_dropout=cfg.get("lora_dropout", 0.05),
        target_modules=cfg.get("lora_target_modules", ["q_proj", "v_proj"]),
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    # Load dataset
    from dataset_loader import load_dataset
    records = load_dataset(dataset_path, strict=True)

    def format_example(record) -> str:
        return (
            f"<|im_start|>user\n{record.instruction}<|im_end|>\n"
            f"<|im_start|>assistant\n{record.response}<|im_end|>"
        )

    formatted = [format_example(r) for r in records]

    training_args = TrainingArguments(
        output_dir=str(output_dir),
        num_train_epochs=cfg.get("num_train_epochs", 3),
        per_device_train_batch_size=cfg.get("per_device_train_batch_size", 1),
        gradient_accumulation_steps=cfg.get("gradient_accumulation_steps", 8),
        learning_rate=cfg.get("learning_rate", 2e-4),
        lr_scheduler_type=cfg.get("lr_scheduler_type", "cosine"),
        warmup_ratio=cfg.get("warmup_ratio", 0.05),
        weight_decay=cfg.get("weight_decay", 0.01),
        max_grad_norm=cfg.get("max_grad_norm", 1.0),
        optim=cfg.get("optim", "paged_adamw_8bit"),
        save_strategy=cfg.get("save_strategy", "steps"),
        save_steps=cfg.get("save_steps", 50),
        save_total_limit=cfg.get("save_total_limit", 3),
        logging_steps=cfg.get("logging_steps", 10),
        report_to=cfg.get("report_to", "none"),
        seed=cfg.get("seed", 42),
        data_seed=cfg.get("data_seed", 42),
        fp16=False,
        bf16=True,
    )

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=formatted,
        max_seq_length=cfg.get("max_seq_length", 512),
        args=training_args,
        resume_from_checkpoint=cfg.get("resume_from_checkpoint"),
    )

    log.info("Starting training. NaN/Inf detection enabled.")
    try:
        trainer.train(resume_from_checkpoint=cfg.get("resume_from_checkpoint"))
    except Exception as exc:
        log.error("Training failed: %s. Saving emergency checkpoint.", exc)
        trainer.save_model(str(output_dir / "emergency_checkpoint"))
        raise

    trainer.save_model(str(output_dir / "final_adapter"))
    tokenizer.save_pretrained(str(output_dir / "final_adapter"))
    log.info("Training complete. Adapter saved to %s", output_dir / "final_adapter")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Jupiter Seed 4B — QLoRA Training Runner",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--config", type=Path, required=True,
        help="Path to YAML training configuration file.",
    )
    parser.add_argument(
        "--dataset-path", type=Path,
        default=None,
        help="Override dataset path from config.",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print cost estimate and exit. Does not start training.",
    )
    parser.add_argument(
        "--seed", type=int, default=None,
        help="Override seed for dry-run estimation only; non-dry-run overrides are rejected.",
    )
    parser.add_argument(
        "--compute-environment", type=Path, default=None,
        help="Required JSON description of the requested non-dry-run compute environment.",
    )
    parser.add_argument(
        "--training-authorization", type=Path, default=None,
        help="Optional explicit human authorization artifact path for non-dry-run execution.",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Training Interlock (V2.4.3)
# ---------------------------------------------------------------------------

EXPECTED_CORPUS_SHA256 = (
    "123fbdaf47a1e6befdb8f3c55ac5f9c5df01d2b473bbdec4417e3c3bfce5ccd0"
)
EXPECTED_DATASET_CONTENT_COMMIT = "2e36f6b977a8af052fced5a532c1168dc1988b6f"
REPO_ROOT = Path(__file__).resolve().parents[2]
READINESS_SCRIPT = Path(__file__).resolve().parent / "readiness_gate.py"

HUMAN_APPROVAL_FIELDS = [
    "approved_by", "approved_at_utc", "authorization_status",
    "signature_or_typed_confirmation", "human_review_status",
    "legal_review_status", "accepted_count", "revised_count",
    "rejected_count", "unresolved_count",
]
COMPUTE_ENVIRONMENT_FIELDS = {
    "device_class", "execution_location", "gpu_model", "maximum_gpu_count",
    "provider", "region", "approved_cost_ceiling_usd",
}
READINESS_BINDING_FIELDS = {
    "artifact_release_commit", "artifact_source_commit", "corpus_sha256",
    "review_package_sha256", "training_config_path", "training_config_sha256",
    "authorization_binding_sha256", "exit_code",
}
GIT_COMMIT_RE = __import__("re").compile(r"^[0-9a-f]{40}$")


class TrainingInterlockError(RuntimeError):
    """Raised for a default-deny authorization or readiness failure."""


def _block(message: str) -> None:
    log.error("TRAINING INTERLOCK: %s", message)
    raise TrainingInterlockError(message)


def _canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def canonical_config_identity(config_path: Path) -> Dict[str, str]:
    """Resolve a config path and bind approval to exact bytes, not aliases."""
    try:
        resolved = config_path.expanduser().resolve(strict=True)
    except OSError as exc:
        _block(f"requested training configuration cannot be resolved: {config_path}")
        raise AssertionError from exc
    if not resolved.is_file():
        _block(f"requested training configuration is not a file: {resolved}")
    try:
        digest = _sha256_bytes(resolved.read_bytes())
    except OSError as exc:
        _block(f"requested training configuration is unreadable: {resolved}")
        raise AssertionError from exc
    return {"path": str(resolved), "sha256": digest}


def _normalize_optional_string(value: Any, field: str) -> Optional[str]:
    if value is None:
        return None
    if not isinstance(value, str):
        _block(f"compute environment field {field!r} must be a string or null")
    normalized = value.strip()
    return normalized.lower() if normalized else None


def canonicalize_compute_environment(raw: Any, label: str) -> Dict[str, Any]:
    """Reject missing, extra, conflicting, or noncanonical material environment fields."""
    if not isinstance(raw, dict):
        _block(f"{label} compute environment must be a JSON object")
    keys = set(raw)
    if keys != COMPUTE_ENVIRONMENT_FIELDS:
        _block(
            f"{label} compute environment fields mismatch: "
            f"missing={sorted(COMPUTE_ENVIRONMENT_FIELDS - keys)} "
            f"unexpected={sorted(keys - COMPUTE_ENVIRONMENT_FIELDS)}"
        )
    device = _normalize_optional_string(raw["device_class"], "device_class")
    location = _normalize_optional_string(raw["execution_location"], "execution_location")
    gpu_model = _normalize_optional_string(raw["gpu_model"], "gpu_model")
    provider = _normalize_optional_string(raw["provider"], "provider")
    region = _normalize_optional_string(raw["region"], "region")
    try:
        gpu_count = int(raw["maximum_gpu_count"])
        cost = float(raw["approved_cost_ceiling_usd"])
    except (TypeError, ValueError):
        _block(f"{label} compute environment GPU count and cost ceiling must be numeric")
        raise AssertionError
    if gpu_count < 0 or cost < 0:
        _block(f"{label} compute environment GPU count and cost ceiling must be non-negative")
    if device not in {"cpu", "gpu"}:
        _block(f"{label} compute environment device_class must be cpu or gpu")
    if location not in {"local", "cloud"}:
        _block(f"{label} compute environment execution_location must be local or cloud")
    if device == "gpu" and (gpu_count < 1 or not gpu_model):
        _block(f"{label} GPU environment requires gpu_model and maximum_gpu_count >= 1")
    if device == "cpu" and (gpu_count != 0 or gpu_model is not None):
        _block(f"{label} CPU environment requires maximum_gpu_count=0 and gpu_model=null")
    if location == "cloud" and (not provider or not region):
        _block(f"{label} cloud environment requires provider and region")
    if location == "local" and (provider is not None or region is not None):
        _block(f"{label} local environment requires provider and region to be null")
    return {
        "device_class": device,
        "execution_location": location,
        "gpu_model": gpu_model,
        "maximum_gpu_count": gpu_count,
        "provider": provider,
        "region": region,
        "approved_cost_ceiling_usd": round(cost, 6),
    }


def load_requested_compute_environment(path: Optional[Path]) -> Dict[str, Any]:
    if path is None:
        _block("requested compute environment is required for non-dry-run training")
    try:
        resolved = path.expanduser().resolve(strict=True)
        raw = json.loads(resolved.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError, UnicodeError) as exc:
        _block(f"requested compute environment cannot be loaded: {type(exc).__name__}")
        raise AssertionError from exc
    return canonicalize_compute_environment(raw, "requested")


def _resolve_commit(revision: str) -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--verify", f"{revision}^{{commit}}"],
            cwd=REPO_ROOT, capture_output=True, text=True,
            encoding="utf-8", errors="replace", timeout=10, check=False,
        )
    except Exception as exc:
        _block(f"commit resolution failure for {revision}: {type(exc).__name__}")
        raise AssertionError from exc
    value = result.stdout.strip().lower()
    if result.returncode != 0 or not GIT_COMMIT_RE.fullmatch(value):
        _block(f"commit resolution failure for {revision}")
    return value


def _review_package_sha256() -> str:
    path = REPO_ROOT / "docs" / "jupiter_seed_4b" / "REVIEWER_PACKAGE.jsonl"
    try:
        return _sha256_bytes(path.read_bytes())
    except OSError as exc:
        _block(f"current review package cannot be read: {type(exc).__name__}")
        raise AssertionError from exc


def _authorization_binding_sha256(auth: Dict[str, Any]) -> str:
    """Hash the completed authorization excluding only the self-binding value."""
    clone = json.loads(_canonical_json(auth))
    readiness = clone.get("approved_readiness")
    if isinstance(readiness, dict):
        readiness.pop("authorization_binding_sha256", None)
    return _sha256_bytes(_canonical_json(clone).encode("utf-8"))


def _load_authorization(auth_path: Path) -> Dict[str, Any]:
    try:
        with auth_path.expanduser().resolve(strict=True).open("r", encoding="utf-8") as fh:
            value = json.load(fh)
    except FileNotFoundError:
        _block(f"Authorization artifact not found: {auth_path}")
    except (json.JSONDecodeError, OSError, UnicodeError) as exc:
        _block(f"Cannot read authorization artifact: {type(exc).__name__}")
    if not isinstance(value, dict):
        _block("authorization artifact must be a JSON object")
    return value


def _check_training_authorization_internal(
    auth_path: Path,
    model_id: str,
    requested_budget_usd: float,
    config_identity: Optional[Dict[str, str]] = None,
    requested_compute_environment: Optional[Dict[str, Any]] = None,
    release_commit: Optional[str] = None,
) -> Dict[str, Any]:
    """Validate every static authorization field before readiness or heavy operations.

    This function never downloads, initializes CUDA, loads a tokenizer, accesses a
    dataset, provisions cloud resources, or calls a paid service.
    """
    auth = _load_authorization(auth_path)
    errors = []
    def check(condition: bool, message: str) -> None:
        if not condition:
            errors.append(message)

    check(str(auth.get("authorization_status", "")) == "APPROVED", "authorization_status must be APPROVED")
    check(str(auth.get("human_review_status", "")) == "COMPLETE", "human_review_status must be COMPLETE")
    try:
        unresolved = int(auth.get("unresolved_count", -1))
    except (ValueError, TypeError):
        unresolved = -1
    check(unresolved == 0, "unresolved_count must be 0")
    check(str(auth.get("legal_review_status", "")) == "APPROVED", "legal_review_status must be APPROVED")
    check(str(auth.get("corpus_sha256", "")) == EXPECTED_CORPUS_SHA256, "corpus_sha256 mismatch")
    check(str(auth.get("dataset_content_commit", "")) == EXPECTED_DATASET_CONTENT_COMMIT,
          "dataset_content_commit mismatch")
    check(str(auth.get("approved_model_id", "")) == model_id, "approved_model_id mismatch")
    try:
        max_budget = float(auth.get("maximum_budget_usd", -1))
    except (TypeError, ValueError):
        max_budget = -1
    check(requested_budget_usd <= max_budget, "requested budget exceeds approved maximum")
    check(bool(str(auth.get("approved_by", "")).strip()) and "HUMAN_REQUIRED" not in str(auth.get("approved_by", "")),
          "approved_by must be a completed human name")
    check(bool(str(auth.get("signature_or_typed_confirmation", "")).strip()) and
          "HUMAN_REQUIRED" not in str(auth.get("signature_or_typed_confirmation", "")),
          "signature_or_typed_confirmation must be completed")
    for field in HUMAN_APPROVAL_FIELDS:
        check("HUMAN_REQUIRED" not in str(auth.get(field, "")), f"{field} contains template placeholder")

    if config_identity is None:
        errors.append("requested training configuration identity is required")
    else:
        approved = auth.get("approved_training_configuration")
        if not isinstance(approved, dict) or set(approved) != {"path", "sha256"}:
            errors.append("approved_training_configuration must contain exactly path and sha256")
        elif approved != config_identity:
            errors.append("approved training configuration path or SHA-256 mismatch")

    if requested_compute_environment is None:
        errors.append("requested compute environment is required")
    else:
        try:
            approved_env = canonicalize_compute_environment(auth.get("approved_compute_environment"), "approved")
            if approved_env != requested_compute_environment:
                errors.append("approved compute environment does not exactly match requested environment")
            if round(max_budget, 6) != requested_compute_environment["approved_cost_ceiling_usd"]:
                errors.append("compute environment cost ceiling must equal maximum_budget_usd")
        except TrainingInterlockError as exc:
            errors.append(str(exc))

    actual_release = release_commit or _resolve_commit("HEAD")
    supplied_release = str(auth.get("readiness_package_commit", "")).strip().lower()
    if not GIT_COMMIT_RE.fullmatch(supplied_release):
        errors.append("readiness_package_commit must be a full 40-character commit hash")
    elif supplied_release != actual_release:
        errors.append("readiness_package_commit must equal the current artifact-release commit")

    if errors:
        for error in errors:
            log.error("TRAINING INTERLOCK: %s", error)
        raise TrainingInterlockError("static authorization validation failed")
    return auth


def check_training_authorization(
    auth_path: Path,
    model_id: str,
    requested_budget_usd: float,
    config_identity: Optional[Dict[str, str]] = None,
    requested_compute_environment: Optional[Dict[str, Any]] = None,
    release_commit: Optional[str] = None,
) -> Dict[str, Any]:
    """Public default-deny authorization API; exits before any heavy operation."""
    try:
        return _check_training_authorization_internal(
            auth_path, model_id, requested_budget_usd, config_identity,
            requested_compute_environment, release_commit,
        )
    except TrainingInterlockError as exc:
        log.error("Training is BLOCKED: %s", exc)
        sys.exit(1)


def run_fresh_readiness(config_identity: Dict[str, str]) -> Dict[str, Any]:
    """Execute the production readiness CLI and bind its result to current evidence."""
    with tempfile.TemporaryDirectory(prefix="jupiter-seed-readiness-") as raw:
        artifact_dir = Path(raw) / "runtime"
        environment = dict(os.environ)
        # PYTEST_CURRENT_TEST is a test-runner implementation detail, not part
        # of the readiness execution environment.
        environment.pop("PYTEST_CURRENT_TEST", None)
        try:
            result = subprocess.run(
                [sys.executable, str(READINESS_SCRIPT), "--artifact-dir", str(artifact_dir)],
                cwd=REPO_ROOT, capture_output=True, text=True,
                encoding="utf-8", errors="replace", timeout=240, check=False,
                env=environment,
            )
        except Exception as exc:
            _block(f"fresh readiness execution failed: {type(exc).__name__}")
            raise AssertionError from exc
    return {
        "artifact_release_commit": _resolve_commit("HEAD"),
        "artifact_source_commit": _resolve_commit("HEAD^"),
        "corpus_sha256": EXPECTED_CORPUS_SHA256,
        "review_package_sha256": _review_package_sha256(),
        "training_config_path": config_identity["path"],
        "training_config_sha256": config_identity["sha256"],
        "exit_code": result.returncode,
    }


def validate_fresh_readiness(auth: Dict[str, Any], readiness: Dict[str, Any]) -> None:
    """Require fresh exit 0 plus an authorization-bound result with exact identities."""
    if readiness.get("exit_code") != 0:
        _block(f"fresh readiness must exit 0; got {readiness.get('exit_code')}")
    approved = auth.get("approved_readiness")
    if not isinstance(approved, dict) or set(approved) != READINESS_BINDING_FIELDS:
        _block("approved_readiness must contain exactly the required binding fields")
    expected = dict(readiness)
    expected["authorization_binding_sha256"] = _authorization_binding_sha256(auth)
    if approved != expected:
        _block("approved_readiness does not exactly match fresh readiness, configuration, corpus, package, and authorization binding")


def authorize_non_dry_run(
    auth_path: Path,
    config_path: Path,
    requested_compute_environment: Dict[str, Any],
    model_id: str,
    requested_budget_usd: float,
    readiness_runner: Callable[[Dict[str, str]], Dict[str, Any]] = run_fresh_readiness,
) -> None:
    """Complete default-deny interlock. Call immediately before run_training only."""
    config_identity = canonical_config_identity(config_path)
    release = _resolve_commit("HEAD")
    auth = check_training_authorization(
        auth_path, model_id, requested_budget_usd, config_identity,
        requested_compute_environment, release,
    )
    readiness = readiness_runner(config_identity)
    validate_fresh_readiness(auth, readiness)
    log.info("Training interlock passed for release %s", release)


def main() -> None:
    args = parse_args()
    cfg = load_config(args.config)

    if args.seed is not None:
        cfg["seed"] = args.seed

    dataset_path = args.dataset_path or Path(cfg.get("dataset_path", "data/diagnostic_seed.jsonl"))

    if args.dry_run:
        # DRY RUN ONLY — NO TRAINING AUTHORIZED
        log.info("DRY RUN ONLY — NO TRAINING AUTHORIZED")
        num_examples = 500  # Default diagnostic size
        if dataset_path.exists():
            with dataset_path.open(encoding="utf-8") as fh:
                num_examples = sum(1 for l in fh if l.strip())
        estimate = estimate_cost(cfg, num_examples)
        print(json.dumps(estimate, indent=2))
        if not estimate["within_budget"]:
            log.error(
                "Estimated cost USD %.2f exceeds authorized limit USD %.2f. "
                "Do not proceed without revised authorization.",
                estimate["estimated_cost_usd"],
                estimate["max_authorized_spend_usd"],
            )
            sys.exit(1)
        log.info(
            "Dry run complete. Estimated cost: USD %.2f. "
            "DRY RUN ONLY — NO TRAINING AUTHORIZED. "
            "Requires human authorization artifact before execution.",
            estimate["estimated_cost_usd"],
        )
        return

    # V2.4.3 TRAINING INTERLOCK: every authorization/readiness check occurs
    # before run_training imports torch/transformers, touches CUDA, downloads,
    # reads data, accesses a network, or could create a billable operation.
    if args.seed is not None or args.dataset_path is not None:
        log.error("TRAINING INTERLOCK: non-dry-run seed or dataset overrides are not approved configuration identity")
        sys.exit(1)
    try:
        requested_environment = load_requested_compute_environment(args.compute_environment)
        auth_path = args.training_authorization or (REPO_ROOT / "docs" / "jupiter_seed_4b" / "TRAINING_AUTHORIZATION.json")
        requested_budget = float(cfg.get("max_authorized_spend_usd", 0.0))
        authorize_non_dry_run(
            auth_path=auth_path,
            config_path=args.config,
            requested_compute_environment=requested_environment,
            model_id=BASE_MODEL_ID,
            requested_budget_usd=requested_budget,
        )
    except TrainingInterlockError:
        log.error("Training is BLOCKED. No model, tokenizer, CUDA, GPU, cloud, API, or training action was reached.")
        sys.exit(1)

    run_training(cfg, dataset_path)


if __name__ == "__main__":
    main()
